### ISSUE TITLE
Incorrect UI behavior

### ISSUE THREAD

**Issue by sadov** [RZhohov/itmo_sh#2]
Cancel button in dialog windows not handled -- application still run and at the last phase application without any data entered in inputbox widgets shows info-window "TRANSACTION number is:" with message "All updates are complete." Can this be fixed?

After entering of wrong data (SENDER, RECEIVER or AMOUNT) I see info-window "TRANSACTION number is:" with message "All updates are complete." again, but transaction was not happen. During the running of shell-script in debug mode I see error message from geth:

Error: authentication needed: password or unlock at web3.js:3104:20 at web3.js:6191:15 at web3.js:5004:36 at <anonymous>:1:1

Seems like "<" redirection sign in message -- the root of problem, without it message shows correctly. Is it possible to remove <> redirection symbols from error message before using in 'dialog' programm?

**Comment by RZhohov** [comment]
Fixed!

**Comment by sadov** [comment]
OK
