### ISSUE TITLE
Geth placement

### ISSUE THREAD

**Issue by sadov** [RZhohov/itmo_sh#3]
In 'itmo' script presented a some code about existence of 'geth' binary, but used only direct calling of them:

TRANSACTION=`./geth --testnet --fast -exec "eth.sendTransaction({from: '$SENDER', to: '$RECEIVER', value: web3.toWei('$AMOUNT', 'ether')})" attach`

Can this be done by calling this program independent of its location?

**Comment by RZhohov** [comment]
Fixed! 

P.S. Don't have geth installed in the system => cannot test it properly, however, we check for geth location in the system.

**Comment by sadov** [comment]
ETH is always an empty string, because we redirecting output to /dev/null:

ETH=$(which geth &>/dev/null)

**Comment by RZhohov** [comment]
I see. 
Will it make sense to change that line to:
ETH=$(which geth 2>/dev/null) ?? 

Thanks.

**Comment by sadov** [comment]
So, what the meaning of this line?

**Comment by RZhohov** [comment]
It means redirect standard error to /dev/null. 
In case if we don't have geth in our system.

**Comment by sadov** [comment]
OK -- fix it.
